---
go_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'

_mysqld_exporter_user: prometheus
_mysqld_exporter_group: prometheus
_mysqld_exporter_binary_install_dir: "/usr/local/bin"
