---
go_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv6'
  armv6l: 'armv6'

go_arch: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"

process_exporter_system_user: "prometheus"
process_exporter_system_group: "prometheus"
_process_exporter_binary_install_dir: "/usr/local/bin"
