---
- name: Create the MySQL Exporter group
  group:
    name: "{{ _mysqld_exporter_group }}"
    state: present
    system: true

- name: Create the MySQL Exporter user
  user:
    name: "{{ _mysqld_exporter_user }}"
    groups: "{{ _mysqld_exporter_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /

- name: propagate locally distributed mysqld_exporter binary
  copy:
    src: "{{ mysqld_exporter_binary_local_dir }}/mysqld_exporter"
    dest: "{{ _mysqld_exporter_binary_install_dir }}/mysqld_exporter"
    mode: 0755
    owner: root
    group: root
  when: mysqld_exporter_binary_local_dir | length > 0
  notify: restart mysqld exporter

- name: Copy the mysqld_exporter systemd service file
  template:
    src: mysqld_exporter.service.j2
    dest: /etc/systemd/system/mysqld_exporter.service
    owner: root
    group: root
    mode: 0644
  #no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"
  notify:
    - restart mysqld exporter
